apiVersion: v1
kind: Pod
metadata:
  name: mypodname
  namespace: mynamespace
spec:
  containers:
  - name: mycontainer
    image: busybox
    command: ['sh','-c','echo $(MY_VAR) && ls -l /config/*']
    envFrom:
    - configMapRef:
      name: special-config    # Contents of the file
    env:
    - name: MY_VAR
      valueFrom:
        configMapKeyRef:
          name: myconfigmap
          key: mykey1
    volumeMounts:
    - name: myconfigmapvolume
      mountPath: "/config"
      readOnly: true
  # Multi container example
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests:
        memory: "600Mi"
        cpu: "400m"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]  
  volumes:
    - name: myconfigmapvolume
      configMap:
        name: myconfigmap

        ## Example of volume mount from host
  volumes:
  - hostPath:
      path: /var/log/webapp
      type: DirectoryOrCreate
    name: log-volume        


    # Example for Secret volume mount
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
  labels:
    name: secret-test
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: ssh-key-secret
  containers:
  - name: ssh-test-container
    image: mySshImage
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"    
